@startuml nimmt

actor Player as user
entity Table as table
entity "Nimmt!" as nimmt

autonumber "<b>[0]"

== 準備フェーズ ==

user -> table: テーブルを作成する
activate table

table --> user: テーブル情報（table_id）
deactivate table

user -> nimmt: テーブルに参加する（table_id, name）
activate nimmt
nimmt -> table: プレイヤーを登録する（table_id, name）
activate table
table --> nimmt: プレイヤー情報（player_id, name）
deactivate table
nimmt -> nimmt: カードとプレイヤーを紐づける
nimmt --> user: JWT（プレイヤー情報）
deactivate nimmt

user -> nimmt: テーブル情報を取得する（JWT）
activate nimmt
nimmt -> table: テーブル情報を取得する（table_id）
activate table
table --> nimmt: テーブル情報（status, players）
deactivate table
nimmt --> user: テーブル情報
deactivate nimmt

user -> nimmt: カードを取得する（JWT）
activate nimmt
nimmt --> user: カード
deactivate nimmt

== 進行フェーズ ==


== 得点計算 ==

@enduml
