openapi: 3.0.0
servers:
  - description: ローカル
    url: https://localhost:8080/v1
info:
  description: ゲームの土台となる API です
  version: "0.1.0"
  title: Game Base API
  contact:
    email: syslink.h.inoue@gmail.com
tags:
  - name: table
paths:
  /tables:
    post:
      tags:
        - table
      summary: テーブルを作成する
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableResponse'
  /tables/{tableId}:
    post:
      tags:
        - table
      summary: テーブルの情報を取得する
      parameters:
        - name: tableId
          in: path
          description: テーブル ID
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableResponse'
  /tables/{tableId}/players:
    post:
      tags:
        - table
      summary: テーブルにプレイヤーが参加する
      parameters:
        - name: tableId
          in: path
          description: テーブル ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: プレイヤー名
                  example: ino_h
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: アクセストークン
                    example: 550e8400-e29b-41d4-a716-446655440000

components:
  schemas:
    TableResponse:
      required:
        - id
      properties:
        id:
          type: string
          description: テーブル ID
          example: 550e8400-e29b-41d4-a716-446655440000
        players:
          description: プレイヤー一覧
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: プレイヤー名
                example: ino_h
